version: 1.0
deploy:

  # configuration part, which is taken at the FIRST deployment of each branch
  bootstrap:
    # folders that are not copied to IONOS webspace
    excludes:

    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
    - wp core download
    - source .env; wp config create --dbname=${WP_DB_NAME} --dbuser=${WP_DB_USER} --dbpass=${WP_DB_PASSWORD} --dbhost=${WP_DB_HOST} --dbcharset=${WP_DB_CHARSET}
    - source .env; wp core install --admin_user=${WP_ADMIN_USER} --admin_user=${WP_ADMIN_EMAIL}
  # configuration part, which is taken at ALL FURTHER deployments of this branch
  recurring:
    excludes:
    - ./
    # commands that are executed at the real webspace NOT at build servers BEFORE copying new files
    pre-deployment-remote-commands:

    post-deployment-remote-commands:
    - wp core update
    - wp plugin update --all
    - wp theme update --all