name: Deploy Now

on:
  - push
  - workflow_dispatch

jobs:
  deploy-now:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: ${{ secrets.IONOS_PROJECT_ID }}
          service-host: api-eu.ionos.space
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Make envfile
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: fmunirdev/envvar-to-dotenv-action@v0.2.0
        with:
          target: .env
          variableNames: WP_DB_NAME,WP_DB_USER,WP_DB_PASSWORD,WP_DB_HOST,WP_DB_CHARSET,WP_ADMIN_USER,WP_ADMIN_EMAIL,WP_ADMIN_PASSWORD,WP_DB_PREFIX,WP_SITE_URL,WP_TITLE
        env:
          WP_DB_NAME: ${{ secrets.WP_DB_NAME }}
          WP_DB_USER: ${{ secrets.WP_DB_USER }}
          WP_DB_PASSWORD: ${{ secrets.WP_DB_PASSWORD }}
          WP_DB_HOST: ${{ secrets.WP_DB_HOST }}
          WP_DB_CHARSET: ${{ secrets.WP_DB_CHARSET }}
          WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
          WP_ADMIN_EMAIL: ${{ secrets.WP_ADMIN_EMAIL }}
          WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
          WP_DB_PREFIX: ${{ github.ref_name }}_
          WP_SITE_URL: ${{ steps.project.outputs.site-url }}
          WP_TITLE: "WordpressTitle"
      - name: Deploy build
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          bootstrap-deploy: ${{ steps.project.outputs.bootstrap-deploy }}
          branch-id: ${{ steps.project.outputs.branch-id }}
          dist-folder: ./
          project: ${{ secrets.IONOS_PROJECT_ID }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          service-host: api-eu.ionos.space
          storage-quota: ${{ steps.project.outputs.storage-quota }}
